version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_DEV_IO_URL={{ project.DEV_IO_URL }}
      - VITE_PROD_IO_URL={{ project.PROD_IO_URL }}
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=development

