version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_DEV_IO_URL
        - VITE_PROD_IO_URL
    ports:
      - "3000:80"
    environment:
      - VITE_DEV_IO_URL
      - VITE_PROD_IO_URL
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3009:3009"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
