version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_DEV_IO_URL
        - VITE_PROD_IO_URL
    ports:
      - "3000:80"
    environment:
      - VITE_DEV_IO_URL
      - VITE_PROD_IO_URL
    depends_on:
      - backend
    networks:
      - dgnet

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - dgnet

networks:
  dgnet:
    driver: bridge
